server:
  port: 8083

spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://3.38.95.110:5433/${POSTGRES_SCHED_DB_NAME}
    username: ${POSTGRES_SCHED_USER}
    password: ${POSTGRES_SCHED_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

  jackson:
    time-zone: Asia/Seoul
    serialization:
      indent_output: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework: INFO
    com.backend: DEBUG
  file:
    name: logs/backend.log

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

firebase:
  credentials:
    json-base64: ${FIREBASE_CREDENTIALS_JSON_BASE64}