server:
  port: 8083

spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://3.38.95.110:5433/${POSTGRES_SCHED_DB_NAME}
    username: ${POSTGRES_SCHED_USER}
    password: ${POSTGRES_SCHED_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  jackson:
    time-zone: Asia/Seoul

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.backend: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

firebase:
  credentials:
    json-base64: ${FIREBASE_CREDENTIALS_JSON_BASE64}