server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: auth-swagger-route
          uri: http://localhost:8091
          predicates:
            - Path=/swagger-ui.html,/swagger-ui/**,/v3/api-docs/**,/webjars/**

        - id: auth-route
          uri: http://localhost:8091  # 로컬 개발 환경에서는 localhost 사용
          predicates:
            - Path=/auth/**

        - id: llm-route
          uri: http://localhost:8092  # 로컬 개발 환경에서는 localhost 사용
          predicates:
            - Path=/llm/**

        - id: logging-route
          uri: http://localhost:8093  # 로컬 개발 환경에서는 localhost 사용
          predicates:
            - Path=/logging/**

        - id: test-route
          uri: http://httpbin.org
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1
