# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:android)

platform :android do
  lane :release do |options|
    gradle(
      task: "clean assembleRelease",
      project_dir: ".",  # openboard_korean 디렉토리 (fastlane의 상위 디렉토리)
      gradle_path: "./gradlew"  # openboard_korean 디렉토리의 gradlew
    )

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
  firebase_cli_token: ENV["FIREBASE_TOKEN"],
      groups: options[:groups],
      release_notes: options[:notes],
      apk_path: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    )
  end
end