server:
  port: 8000

logging:
  level:
    com.gateway.filter: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.data.redis: DEBUG

management:
  server:
    base-path: /actuator
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

jwt:
  secret: ${JWT_SECRET_KEY}

# Redis 설정 (Rate Limiter 전용)
spring:
  redis:
    host: redis-ratelimiter  # Docker Compose 서비스 이름
    port: 6380  # 커스텀 포트
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

  application:
    name: moca-gateway

  cloud:
    gateway:
      routes:
        # 1) 인증 서비스 --------------------------------------------
        - id: auth-route
          uri: http://moca-auth-service:8082  # Docker Compose 서비스 이름
          predicates:
            - Path=/auth/**
          metadata:
            description: "Authentication Service - User login and token management"

        # 2) 백엔드 서비스 ----------------------------------------
        - id: backend-route
          uri: http://moca-backend-service:8083  # Docker Compose 서비스 이름
          predicates:
            - Path=/api/**
          metadata:
            description: "Main Backend Service - User profiles and schedules"

        # 3) RAG 서비스 (Rate Limit 적용) --------------------------
        - id: rag-route
          uri: http://moca-rag-service:8090  # Docker Compose 서비스 이름
          predicates:
            - Path=/rag/**
          filters:
            - name: RequestRateLimiter
              args:
                rate-limiter: "#{@ragServerRateLimiter}"
                key-resolver: "#{@userKeyResolver}"
          metadata:
            description: "RAG Service with Rate Limiting - AI assistance"

      # CORS 설정
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false
            maxAge: 3600

      # Health Check 설정
      httpclient:
        connect-timeout: 3000
        response-timeout: 5s